### ISSUE TITLE
Feature Request: Rule34 site

### ISSUE THREAD

**Issue by ibigfire** [Jintaku/Jintaku-Cogs-V3#3]
Given that the website rule34.xxx seemingly uses a similar backend as danbooru, gelbooru, and konachan it would be really handy if a separate rule34 command was added to pull images from that site.

I am trying to replace my old Nadeko bot completely with Red and that's one of the features that no cogs have implemented yet as far as I can tell.  Sorry if you're not taking feature requests, I completely understand if that is the case!  Just wanted to mention it as others coming from that bot may also have an interest as well.

**Comment by lionirdeadman** [comment]
I thought about adding more but if I do, I'd add them also to the `booru` command in the best of worlds, I believe I should add a setting to set which image boards are search using that function otherwise I will reach 500 pages which could start causing a recursion bug with the way menus work in Red if people decide to see all of the pages, furthermore it'd be more data to process and to request.

I'll have to think about what I should do to keep the aggregated image board command but also add more image boards as I should.

Also, please do ask for new features, It really helps me to motivate me to work on things knowing that people actually want me to work on it and seeing them have fun with it.

**Comment by lionirdeadman** [comment]
It's done! Now you can use `[p]r34` to search exclusively for it and if you want `[p]booru` to include r34 posts, you can do so with `[p]booruset guild boards`!

As I said, feel free to ask for more feature requests (or report bugs if any)

**Comment by ibigfire** [comment]
Oh yay, awesome!  Thanks so much!  I'll try to test it out and see if I can break it this weekend.  :)  You rock!
