### ISSUE TITLE
[Gamesearch] API v3 Shutting Down on 26th October, 2020

### ISSUE THREAD

**Issue by Mibo5354** [Jintaku/Jintaku-Cogs-V3#40]
The current Gamesearch cog uses the igdb v3 api which is going to shut down on 26/10/20
The new v4 api uses a client ID and secret instead of a single api key.
https://api-docs.igdb.com/#upgrading-to-v4-from-v3

**Comment by lionirdeadman** [comment]
This seems fairly easy to do. Thanks for the alert!

**Comment by lionirdeadman** [comment]
Instead of moving to v4 and requiring people to get a new account (which requires 2FA with a phone number potentially), I've decided to use https://rawg.io/ since it does not require an account at all to use their API. This'll make it easier for people to get the cog working since it doesn't require a key and well, avoid them the pain of making a throwaway like what was previously needed. 

I'll keep this issue open until I make it work with rawg. Hope it's understandable.

**Comment by lionirdeadman** [comment]
It's been done!
